spring:
  jpa:
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:mysql://localhost:3306/book-market-api-db?useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: mynewpassword
  jackson:
    default-property-inclusion: non_null

#      spring.datasource.url=jdbc:mysql://localhost:3306/cars-api-db?useSSL=false&allowPublicKeyRetrieval=true
#      spring.datasource.username=root
#      spring.datasource.password=mynewpassword